Internal Server Error: /get_gigachat_token/
"POST /get_gigachat_token/ HTTP/1.1" 500 142
Internal Server Error: /get_gigachat_token/
"POST /get_gigachat_token/ HTTP/1.1" 500 142
Internal Server Error: /chat/
Traceback (most recent call last):
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\smart_study_buddy\smart_study_buddy\views.py", line 192, in chat_view
    return render(request, 'chat.html')
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\ִלטענטי\AppData\Roaming\Python\Python39\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 7: 'static'. Did you forget to register or load this tag?
"GET /chat/ HTTP/1.1" 500 136645
